### ISSUE TITLE
How can I push this service broker as an application on CF

### ISSUE THREAD

**Issue by cfmagnum** [starkandwayne/kafka-service-broker#5]
I want to push this broker as an application and it should be available in the marketplace.
I tried pushing it normally with the CF PUSH but it not working.
Can you please let me if i am going in a wrong direction or i am missing something. 

Thanks in advance.

**Comment by drnic** [comment]
@cfmagnum it should "just work". The application has a `Procfile` and its dependencies are vendored.

You'll need to use `cf set-env` to set the required `BROKER_X` and `ZOOKEEPER_PEERS` variables before starting the app. https://github.com/starkandwayne/kafka-service-broker#configuration

Like all the client apps, you'll need a CF Security Group for the app's space that allows the broker app to connect to Zookeeper.
